version: "3"

services:
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: poc_hexagonal_mongo_4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=poc_hexagonal_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - sgbd-compose-network

networks:
  sgbd-compose-network:
    driver: bridge
